version: "2"
services:
  api:
    build: ./api
    container_name: "node-api"
    restart: always
    ports:
      - "3000:3000"
  server:
    image: abiosoft/caddy
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    links:
      - api
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "./caddy:/root/.caddy"
      - "./web:/srv"
